package com.company.lms.web;

import org.springframework.http.ResponseEntity;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.security.access.prepost.PreAuthorize;
import org.springframework.security.core.Authentication;
import org.springframework.web.bind.annotation.*;
import java.util.*;

@RestController @RequestMapping("/api/courses")
public class CourseController extends ApiSupport {
 private final JdbcTemplate db; public CourseController(JdbcTemplate db){this.db=db;}
 @GetMapping public Map<String,Object> all(@RequestParam(required=false) String category,@RequestParam(required=false) String search, Authentication auth) {
   boolean employee=auth!=null && "employee".equals(role(auth)); List<Object> p=new ArrayList<>();
   String sql=employee ? "SELECT c.*,u.full_name creator_name,COUNT(DISTINCT l.id) total_lessons,COALESCE(SUM(l.duration_mins),0) total_duration_mins,ca.status assignment_status,ca.due_date,ca.completed_at FROM course_assignments ca JOIN courses c ON c.id=ca.course_id LEFT JOIN users u ON u.id=c.created_by LEFT JOIN lessons l ON l.course_id=c.id WHERE ca.user_id=?" : "SELECT c.*,u.full_name creator_name,COUNT(DISTINCT l.id) total_lessons,COALESCE(SUM(l.duration_mins),0) total_duration_mins,COUNT(DISTINCT ca.id) enrolled_count FROM courses c LEFT JOIN users u ON u.id=c.created_by LEFT JOIN lessons l ON l.course_id=c.id LEFT JOIN course_assignments ca ON ca.course_id=c.id WHERE c.is_published=TRUE";
   if(employee)p.add(userId(auth)); if(category!=null){sql+=" AND c.category=?";p.add(category);} if(search!=null){sql+=" AND (c.title ILIKE ? OR c.description ILIKE ?)";p.add("%"+search.trim()+"%");p.add("%"+search.trim()+"%");}
   sql+=" GROUP BY c.id,u.full_name"+(employee?",ca.status,ca.due_date,ca.completed_at":"")+" ORDER BY c.is_mandatory DESC,c.created_at DESC";
   return ok("courses",db.queryForList(sql,p.toArray()));
 }
 @GetMapping("/{id}") public ResponseEntity<?> one(@PathVariable long id, Authentication auth) {
   List<Map<String,Object>> courses=db.queryForList("SELECT c.*,u.full_name creator_name,u.email creator_email FROM courses c LEFT JOIN users u ON u.id=c.created_by WHERE c.id=?",id); if(courses.isEmpty())return ResponseEntity.status(404).body(Map.of("success",false,"message","Training course not found."));
   Map<String,Object> course=new LinkedHashMap<>(courses.getFirst()); List<Map<String,Object>> chapters=db.queryForList("SELECT * FROM chapters WHERE course_id=? ORDER BY sequence_order,id",id); List<Map<String,Object>> lessons=db.queryForList("SELECT id,chapter_id,course_id,title,content_type,duration_mins,sequence_order,video_url,content FROM lessons WHERE course_id=? ORDER BY sequence_order,id",id); List<Map<String,Object>> quizzes=db.queryForList("SELECT id,course_id,title,passing_score,time_limit_mins FROM quizzes WHERE course_id=?",id);
   List<Long> completed=new ArrayList<>(); Map<String,Object> assignment=null, certificate=null; List<Map<String,Object>> submissions=List.of();
   if(auth!=null){long uid=userId(auth); completed=db.queryForList("SELECT lesson_id FROM lesson_progress WHERE user_id=? AND course_id=? AND completed=TRUE",Long.class,uid,id); var ass=db.queryForList("SELECT * FROM course_assignments WHERE user_id=? AND course_id=?",uid,id); assignment=ass.isEmpty()?null:ass.getFirst(); if(!quizzes.isEmpty())submissions=db.queryForList("SELECT * FROM quiz_submissions WHERE user_id=? AND quiz_id=? ORDER BY submitted_at DESC",uid,quizzes.getFirst().get("id"));var cert=db.queryForList("SELECT * FROM certificates WHERE user_id=? AND course_id=?",uid,id);certificate=cert.isEmpty()?null:cert.getFirst();}
   List<Map<String,Object>> nested=new ArrayList<>(); for(var ch:chapters){Map<String,Object> c=new LinkedHashMap<>(ch);List<Map<String,Object>> ls=new ArrayList<>();for(var lesson:lessons)if(((Number)lesson.get("chapter_id")).longValue()==((Number)ch.get("id")).longValue()){Map<String,Object> l=new LinkedHashMap<>(lesson);l.put("is_completed",completed.contains(((Number)lesson.get("id")).longValue()));ls.add(l);}c.put("lessons",ls);nested.add(c);} course.put("chapters",nested);course.put("total_lessons",lessons.size());course.put("quizzes",quizzes);course.put("user_progress",Map.of("completed_count",completed.size(),"percent",lessons.isEmpty()?0:Math.round(completed.size()*100.0/lessons.size()),"completed_lesson_ids",completed,"assignment",assignment,"quiz_submissions",submissions,"certificate",certificate));return ResponseEntity.ok(ok("course",course));
 }
 @PostMapping @PreAuthorize("hasAnyRole('TRAINER','ADMIN')") public ResponseEntity<?> create(@RequestBody Map<String,Object>b,Authentication a){String title=String.valueOf(b.getOrDefault("title","")).trim();if(title.isBlank())return ResponseEntity.badRequest().body(Map.of("success",false,"message","Course title is required."));String slug=title.toLowerCase().replaceAll("[^a-z0-9]+","-").replaceAll("(^-|-$)","")+"-"+(1000+new Random().nextInt(9000));Map<String,Object> c=db.queryForMap("INSERT INTO courses(title,slug,description,category,is_mandatory,estimated_duration_hours,created_by) VALUES(?,?,?,?,?,?,?) RETURNING *",title,slug,b.getOrDefault("description",""),b.getOrDefault("category","General"),bool(b,"is_mandatory"),number(b,"estimated_duration_hours",1),userId(a));return ResponseEntity.status(201).body(Map.of("success",true,"message","Course created successfully.","course",c));}
 @PutMapping("/{id}") @PreAuthorize("hasAnyRole('TRAINER','ADMIN')") public ResponseEntity<?> update(@PathVariable long id,@RequestBody Map<String,Object>b){int count=db.update("UPDATE courses SET title=COALESCE(?,title),description=COALESCE(?,description),category=COALESCE(?,category),is_mandatory=COALESCE(?,is_mandatory),estimated_duration_hours=COALESCE(?,estimated_duration_hours),is_published=COALESCE(?,is_published),updated_at=CURRENT_TIMESTAMP WHERE id=?",b.get("title"),b.get("description"),b.get("category"),b.get("is_mandatory"),b.get("estimated_duration_hours"),b.get("is_published"),id);return count==0?ResponseEntity.status(404).body(Map.of("success",false,"message","Course not found.")):ResponseEntity.ok(message("Course updated successfully."));}
 @DeleteMapping("/{id}") @PreAuthorize("hasRole('ADMIN')") public ResponseEntity<?> delete(@PathVariable long id){return db.update("DELETE FROM courses WHERE id=?",id)==0?ResponseEntity.status(404).body(Map.of("success",false,"message","Course not found.")):ResponseEntity.ok(message("Course deleted successfully."));}
 @PostMapping("/{courseId}/chapters") @PreAuthorize("hasAnyRole('TRAINER','ADMIN')") public ResponseEntity<?> chapter(@PathVariable long courseId,@RequestBody Map<String,Object>b){Map<String,Object> r=db.queryForMap("INSERT INTO chapters(course_id,title,sequence_order) VALUES(?,?,?) RETURNING *",courseId,b.get("title"),number(b,"sequence_order",1));return ResponseEntity.status(201).body(ok("chapter",r));}
 @PostMapping("/{courseId}/chapters/{chapterId}/lessons") @PreAuthorize("hasAnyRole('TRAINER','ADMIN')") public ResponseEntity<?> lesson(@PathVariable long courseId,@PathVariable long chapterId,@RequestBody Map<String,Object>b){Map<String,Object> r=db.queryForMap("INSERT INTO lessons(chapter_id,course_id,title,content_type,content,video_url,duration_mins,sequence_order) VALUES(?,?,?,?,?,?,?,?) RETURNING *",chapterId,courseId,b.get("title"),b.getOrDefault("content_type","text"),b.getOrDefault("content",""),b.get("video_url"),number(b,"duration_mins",10),number(b,"sequence_order",1));return ResponseEntity.status(201).body(ok("lesson",r));}
 private boolean bool(Map<String,Object>b,String k){return Boolean.parseBoolean(String.valueOf(b.getOrDefault(k,false)));} private Number number(Map<String,Object>b,String k,Number d){Object v=b.get(k);return v instanceof Number n?n:d;}
}
