package com.company.lms.web;
import com.company.lms.service.DepartmentEnrollmentService;
import org.springframework.http.ResponseEntity; import org.springframework.jdbc.core.JdbcTemplate; import org.springframework.security.access.prepost.PreAuthorize; import org.springframework.security.core.Authentication; import org.springframework.web.bind.annotation.*; import java.util.*;
@RestController @RequestMapping("/api/departments") public class DepartmentController extends ApiSupport {
 private final JdbcTemplate db; private final DepartmentEnrollmentService departmentEnrollments;
 public DepartmentController(JdbcTemplate db, DepartmentEnrollmentService departmentEnrollments){this.db=db;this.departmentEnrollments=departmentEnrollments;}
 @GetMapping public Map<String,Object> all(){return ok("departments",db.queryForList("SELECT d.*,(SELECT COUNT(DISTINCT u.id) FROM user_departments ud JOIN users u ON u.id=ud.user_id AND u.is_active=TRUE AND u.role='employee' WHERE ud.department_id=d.id) employee_count FROM departments d ORDER BY d.name"));}
 @GetMapping("/my-departments") @PreAuthorize("hasAnyRole('TRAINER','ADMIN')") public Map<String,Object> mine(Authentication a){String sql="admin".equals(role(a))?"SELECT d.*,(SELECT COUNT(DISTINCT u.id) FROM user_departments ud JOIN users u ON u.id=ud.user_id AND u.is_active=TRUE AND u.role='employee' WHERE ud.department_id=d.id) employee_count FROM departments d ORDER BY d.name":"SELECT d.*,(SELECT COUNT(DISTINCT u.id) FROM user_departments ud JOIN users u ON u.id=ud.user_id AND u.is_active=TRUE AND u.role='employee' WHERE ud.department_id=d.id) employee_count FROM departments d WHERE d.id IN (SELECT td.department_id FROM trainer_departments td WHERE td.trainer_id=?) ORDER BY d.name";return ok("departments","admin".equals(role(a))?db.queryForList(sql):db.queryForList(sql,userId(a)));}
 @GetMapping("/trainer-assignments") @PreAuthorize("hasRole('ADMIN')") public Map<String,Object> mappings(){return ok("assignments",db.queryForList("SELECT td.id,td.trainer_id,td.department_id,td.assigned_at,u.full_name trainer_name,u.email trainer_email,d.name department_name FROM trainer_departments td JOIN users u ON u.id=td.trainer_id JOIN departments d ON d.id=td.department_id ORDER BY d.name,u.full_name"));}
 @PostMapping @PreAuthorize("hasRole('ADMIN')") public ResponseEntity<?> create(@RequestBody Map<String,Object>b){String name=plain(b.get("name"),120);if(name==null||name.isBlank())return ResponseEntity.badRequest().body(Map.of("success",false,"message","Department name is required."));Map<String,Object>d=db.queryForMap("INSERT INTO departments(name,description) VALUES(?,?) RETURNING *",name,plain(b.get("description"),500));return ResponseEntity.status(201).body(Map.of("success",true,"message","Department created successfully.","department",d));}
 @PutMapping("/{id}") @PreAuthorize("hasRole('ADMIN')") public ResponseEntity<?> update(@PathVariable long id,@RequestBody Map<String,Object>b){return db.update("UPDATE departments SET name=COALESCE(?,name),description=COALESCE(?,description) WHERE id=?",b.containsKey("name")?plain(b.get("name"),120):null,b.containsKey("description")?plain(b.get("description"),500):null,id)==0?ResponseEntity.status(404).body(Map.of("success",false,"message","Department not found.")):ResponseEntity.ok(message("Department updated."));}
 @DeleteMapping("/{id}") @PreAuthorize("hasRole('ADMIN')") @org.springframework.transaction.annotation.Transactional public ResponseEntity<?> delete(@PathVariable long id){db.update("UPDATE users SET department_id=NULL WHERE department_id=?",id);int removed=db.update("DELETE FROM departments WHERE id=?",id);db.update("UPDATE users SET role='employee' WHERE role='trainer' AND NOT EXISTS(SELECT 1 FROM trainer_departments WHERE trainer_id=users.id)");return removed==0?ResponseEntity.status(404).body(Map.of("success",false,"message","Department not found.")):ResponseEntity.ok(message("Department deleted."));}
 @GetMapping("/{id}/employees") public Map<String,Object> employees(@PathVariable long id){return ok("employees",db.queryForList("SELECT u.id,u.employee_id,u.full_name,u.email,u.role,u.designation,u.is_active FROM user_departments ud JOIN users u ON u.id=ud.user_id WHERE ud.department_id=? AND u.is_active=TRUE ORDER BY u.role,u.full_name",id));}
 @PostMapping("/{id}/members") @PreAuthorize("hasRole('ADMIN')") @org.springframework.transaction.annotation.Transactional public Map<String,Object> add(@PathVariable long id,@RequestBody Map<String,Object>b){
   Object uIdObj = b.get("user_id");
   if(uIdObj == null || uIdObj.toString().isBlank()){
     throw new IllegalArgumentException("user_id is required");
   }
   long userId = Long.parseLong(uIdObj.toString().trim());
   db.update("INSERT INTO user_departments(user_id,department_id) VALUES(?,?) ON CONFLICT DO NOTHING", userId, (int)id);
   db.update("UPDATE users SET department_id=? WHERE id=? AND department_id IS NULL", (int)id, userId);
   departmentEnrollments.catchUpMember(userId, List.of(id));
   return message("Employee added to department.");
 }
 @DeleteMapping("/{id}/members/{userId}") @PreAuthorize("hasRole('ADMIN')") @org.springframework.transaction.annotation.Transactional public Map<String,Object> remove(@PathVariable long id,@PathVariable long userId){
   db.update("DELETE FROM user_departments WHERE user_id=? AND department_id=?", userId, id);
   db.update("UPDATE users SET department_id=(SELECT min(department_id) FROM user_departments WHERE user_id=?) WHERE id=? AND department_id=?", userId, userId, id);
   // Management must be a subset of membership: removing them from this dept also revokes training it.
   db.update("DELETE FROM trainer_departments WHERE trainer_id=? AND department_id=?", userId, id);
   db.update("UPDATE users SET role='employee' WHERE id=? AND role='trainer' AND NOT EXISTS(SELECT 1 FROM trainer_departments WHERE trainer_id=?)", userId, userId);
   return message("Employee removed from department.");
 }
 @PostMapping("/{id}/trainers") @PreAuthorize("hasRole('ADMIN')") @org.springframework.transaction.annotation.Transactional public Map<String,Object> assign(@PathVariable long id,@RequestBody Map<String,Object>b,Authentication a){Object t=b.get("trainer_id");if(t==null||t.toString().isBlank())throw new IllegalArgumentException("trainer_id is required");long trainerId=Long.parseLong(t.toString().trim());if(!db.queryForList("SELECT 1 FROM users WHERE id=? AND role='admin'",trainerId).isEmpty())throw new IllegalArgumentException("Admins cannot be assigned as department trainers.");db.update("INSERT INTO trainer_departments(trainer_id,department_id,assigned_by) VALUES(?,?,?) ON CONFLICT(trainer_id,department_id) DO NOTHING",trainerId,id,userId(a));db.update("INSERT INTO user_departments(user_id,department_id) VALUES(?,?) ON CONFLICT DO NOTHING",trainerId,id);db.update("UPDATE users SET department_id=? WHERE id=? AND department_id IS NULL",id,trainerId);db.update("UPDATE users SET role='trainer' WHERE id=? AND role<>'admin'",trainerId);return message("Trainer assigned to department.");}
 @DeleteMapping("/{id}/trainers/{trainerId}") @PreAuthorize("hasRole('ADMIN')") @org.springframework.transaction.annotation.Transactional public Map<String,Object> unassign(@PathVariable long id,@PathVariable long trainerId){db.update("DELETE FROM trainer_departments WHERE trainer_id=? AND department_id=?",trainerId,id);db.update("UPDATE users SET role='employee' WHERE id=? AND role='trainer' AND NOT EXISTS(SELECT 1 FROM trainer_departments WHERE trainer_id=?)",trainerId,trainerId);return message("Trainer removed from department.");}
}
