package com.company.lms.web;
import org.springframework.http.ResponseEntity; import org.springframework.jdbc.core.JdbcTemplate; import org.springframework.security.access.prepost.PreAuthorize; import org.springframework.security.core.Authentication; import org.springframework.web.bind.annotation.*; import java.util.*;
@RestController @RequestMapping("/api/departments") public class DepartmentController extends ApiSupport {
 private final JdbcTemplate db; public DepartmentController(JdbcTemplate db){this.db=db;}
 @GetMapping public Map<String,Object> all(){return ok("departments",db.queryForList("SELECT d.*,COUNT(u.id) employee_count FROM departments d LEFT JOIN users u ON u.department_id=d.id AND u.is_active=TRUE GROUP BY d.id ORDER BY d.name"));}
 @GetMapping("/my-departments") @PreAuthorize("hasAnyRole('TRAINER','ADMIN')") public Map<String,Object> mine(Authentication a){String sql="admin".equals(role(a))?"SELECT d.*,COUNT(u.id) employee_count FROM departments d LEFT JOIN users u ON u.department_id=d.id AND u.is_active=TRUE GROUP BY d.id ORDER BY d.name":"SELECT d.*,COUNT(u.id) employee_count FROM trainer_departments td JOIN departments d ON d.id=td.department_id LEFT JOIN users u ON u.department_id=d.id AND u.is_active=TRUE WHERE td.trainer_id=? GROUP BY d.id ORDER BY d.name";return ok("departments","admin".equals(role(a))?db.queryForList(sql):db.queryForList(sql,userId(a)));}
 @GetMapping("/trainer-assignments") @PreAuthorize("hasRole('ADMIN')") public Map<String,Object> mappings(){return ok("assignments",db.queryForList("SELECT td.id,td.trainer_id,td.department_id,td.assigned_at,u.full_name trainer_name,u.email trainer_email,d.name department_name FROM trainer_departments td JOIN users u ON u.id=td.trainer_id JOIN departments d ON d.id=td.department_id ORDER BY d.name,u.full_name"));}
 @PostMapping @PreAuthorize("hasRole('ADMIN')") public ResponseEntity<?> create(@RequestBody Map<String,Object>b){if(b.get("name")==null)return ResponseEntity.badRequest().body(Map.of("success",false,"message","Department name is required."));Map<String,Object>d=db.queryForMap("INSERT INTO departments(name,description) VALUES(?,?) RETURNING *",b.get("name").toString().trim(),b.getOrDefault("description",""));return ResponseEntity.status(201).body(Map.of("success",true,"message","Department created successfully.","department",d));}
 @PutMapping("/{id}") @PreAuthorize("hasRole('ADMIN')") public ResponseEntity<?> update(@PathVariable long id,@RequestBody Map<String,Object>b){return db.update("UPDATE departments SET name=COALESCE(?,name),description=COALESCE(?,description) WHERE id=?",b.get("name"),b.get("description"),id)==0?ResponseEntity.status(404).body(Map.of("success",false,"message","Department not found.")):ResponseEntity.ok(message("Department updated."));}
 @DeleteMapping("/{id}") @PreAuthorize("hasRole('ADMIN')") public ResponseEntity<?> delete(@PathVariable long id){return db.update("DELETE FROM departments WHERE id=?",id)==0?ResponseEntity.status(404).body(Map.of("success",false,"message","Department not found.")):ResponseEntity.ok(message("Department deleted."));}
 @GetMapping("/{id}/employees") public Map<String,Object> employees(@PathVariable long id){return ok("employees",db.queryForList("SELECT id,employee_id,full_name,email,role,designation,is_active FROM users WHERE department_id=? AND is_active=TRUE ORDER BY full_name",id));}
 @PostMapping("/{id}/members") @PreAuthorize("hasRole('ADMIN')") public Map<String,Object> add(@PathVariable long id,@RequestBody Map<String,Object>b){db.update("UPDATE users SET department_id=? WHERE id=?",id,b.get("user_id"));return message("Employee added to department.");}
 @DeleteMapping("/{id}/members/{userId}") @PreAuthorize("hasRole('ADMIN')") public Map<String,Object> remove(@PathVariable long userId){db.update("UPDATE users SET department_id=NULL WHERE id=?",userId);return message("Employee removed from department.");}
 @PostMapping("/{id}/trainers") @PreAuthorize("hasRole('ADMIN')") public Map<String,Object> assign(@PathVariable long id,@RequestBody Map<String,Object>b,Authentication a){db.update("INSERT INTO trainer_departments(trainer_id,department_id,assigned_by) VALUES(?,?,?) ON CONFLICT(trainer_id,department_id) DO NOTHING",b.get("trainer_id"),id,userId(a));return message("Trainer assigned to department.");}
 @DeleteMapping("/{id}/trainers/{trainerId}") @PreAuthorize("hasRole('ADMIN')") public Map<String,Object> unassign(@PathVariable long id,@PathVariable long trainerId){db.update("DELETE FROM trainer_departments WHERE trainer_id=? AND department_id=?",trainerId,id);return message("Trainer removed from department.");}
}
