package com.company.lms.web;
import org.springframework.http.ResponseEntity; import org.springframework.jdbc.core.JdbcTemplate; import org.springframework.security.core.Authentication; import org.springframework.web.bind.annotation.*; import java.security.SecureRandom; import java.util.*;
@RestController @RequestMapping("/api/progress") public class ProgressController extends ApiSupport {
 private final JdbcTemplate db; private final SecureRandom random=new SecureRandom(); public ProgressController(JdbcTemplate db){this.db=db;}
 @PostMapping("/toggle-lesson") public ResponseEntity<?> toggle(@RequestBody Map<String,Object>b,Authentication a){Object course=b.get("course_id"),lesson=b.get("lesson_id");if(course==null||lesson==null)return ResponseEntity.badRequest().body(Map.of("success",false,"message","Course ID and Lesson ID are required."));boolean done=!Boolean.FALSE.equals(b.get("completed"));if(done)db.update("INSERT INTO lesson_progress(user_id,lesson_id,course_id,completed) VALUES(?,?,?,TRUE) ON CONFLICT(user_id,lesson_id) DO UPDATE SET completed=TRUE,completed_at=CURRENT_TIMESTAMP",userId(a),lesson,course);else db.update("DELETE FROM lesson_progress WHERE user_id=? AND lesson_id=?",userId(a),lesson);db.update("INSERT INTO course_assignments(course_id,user_id,assigned_by,status) VALUES(?,?,?,'in_progress') ON CONFLICT(course_id,user_id) DO UPDATE SET status='in_progress' WHERE course_assignments.status='enrolled'",course,userId(a),userId(a));int total=db.queryForObject("SELECT COUNT(*) FROM lessons WHERE course_id=?",Integer.class,course),completed=db.queryForObject("SELECT COUNT(*) FROM lesson_progress WHERE user_id=? AND course_id=? AND completed=TRUE",Integer.class,userId(a),course);boolean quizPassed=db.queryForObject("SELECT NOT EXISTS(SELECT 1 FROM quizzes q WHERE q.course_id=? AND NOT EXISTS(SELECT 1 FROM quiz_submissions s WHERE s.quiz_id=q.id AND s.user_id=? AND s.passed=TRUE))",Boolean.class,course,userId(a));String code=null;if(total>0&&completed>=total&&quizPassed){db.update("UPDATE course_assignments SET status='completed',completed_at=CURRENT_TIMESTAMP WHERE course_id=? AND user_id=? AND completed_at IS NULL",course,userId(a));code=certificate(course,userId(a));}Map<String,Object> progress=new LinkedHashMap<>();progress.put("total_lessons",total);progress.put("completed_lessons",completed);progress.put("percent",total==0?0:Math.round(completed*100.0/total));progress.put("all_lessons_done",total>0&&completed>=total);progress.put("quiz_passed",quizPassed);progress.put("certificate_issued",code!=null);progress.put("certificate_code",code);return ResponseEntity.ok(Map.of("success",true,"completed",done,"progress",progress));}
 @GetMapping("/certificates/my") public Map<String,Object> mine(Authentication a){return ok("certificates",db.queryForList("SELECT cert.id,cert.certificate_code,cert.issued_at,c.title course_title,c.category course_category,u.full_name employee_name,u.employee_id,d.name department_name FROM certificates cert JOIN courses c ON c.id=cert.course_id JOIN users u ON u.id=cert.user_id LEFT JOIN departments d ON d.id=u.department_id WHERE cert.user_id=? ORDER BY cert.issued_at DESC",userId(a)));}
 @GetMapping("/certificates/verify/{code}") public ResponseEntity<?> verify(@PathVariable String code){var rows=db.queryForList("SELECT cert.id,cert.certificate_code,cert.issued_at,c.title course_title,c.category course_category,c.estimated_duration_hours,u.full_name employee_name,u.employee_id,u.designation,d.name department_name FROM certificates cert JOIN courses c ON c.id=cert.course_id JOIN users u ON u.id=cert.user_id LEFT JOIN departments d ON d.id=u.department_id WHERE cert.certificate_code=?",code);return rows.isEmpty()?ResponseEntity.status(404).body(Map.of("success",false,"message","Certificate verification failed: Invalid certificate code.")):ResponseEntity.ok(ok("certificate",rows.getFirst()));}
 String certificate(Object course,long user){var existing=db.queryForList("SELECT certificate_code FROM certificates WHERE course_id=? AND user_id=?",course,user);if(!existing.isEmpty())return (String)existing.getFirst().get("certificate_code");String code="CERT-"+Long.toHexString(random.nextLong()).replace('-','X').toUpperCase()+"-"+(System.currentTimeMillis()%10000);db.update("INSERT INTO certificates(certificate_code,user_id,course_id) VALUES(?,?,?)",code,user,course);return code;}
}
